const interactiveWorkflowDemo = {
  nodeTitle: { title: "Paletă de noduri" },
  nodeOneTitle: { title: "Gestionarea documentelor" },
  runBtn: { title: "Rulează fluxul de lucru" },
  saveBtn: { title: "Salvează" },
  shareBtn: { title: "Partajează" },
  nodeOneOptionOneTitle: { title: "Încarcă contractul" },
  nodeOneOptionOneDescription: { title: "Încarcă contractul de închiriere" },
  nodeOneOptionTwoTitle: { title: "Analizează contractul" },
  nodeOneOptionTwoDescription: { title: "Extrage clauzele contractuale" },
  nodeTwoTitle: { title: "Cercetare juridică" },
  nodeTwoOptionOneTitle: { title: "Cercetează drepturile" },
  nodeTwoOptionOneDescription: { title: "Cercetează drepturile chiriașului" },
  nodeTwoOptionTwoTitle: { title: "Clasifică litigiul" },
  nodeTwoOptionTwoDescription: { title: "Încadrează litigiul" },
  nodeThreeTitle: { title: "Strategie" },
  nodeThreeOptionOneTitle: { title: "Strategie juridică" },
  nodeThreeOptionOneDescription: { title: "Generează recomandări juridice" },
  nodeCardOneTitle: { title: "Încarcă contractul de închiriere" },
  nodeCardOneDescription: { title: "Încarcă contractul de închiriere" },
  nodeCardTwoTitle: { title: "Analizează clauzele contractuale" },
  nodeCardTwoDescription: { title: "Extrage clauzele, termenii și obligațiile cheie" },
  nodeCardThreeTitle: { title: "Cercetează drepturile chiriașului" },
  nodeCardThreeDescription: { title: "Cercetează drepturile și protecțiile aplicabile ale chiriașului" },
  nodeCardFourTitle: { title: "Clasifică tipul litigiului" },
  nodeCardFourDescription: { title: "Încadrează tipul litigiului și nivelul de gravitate" },
  nodeCardFiveTitle: { title: "Strategie juridică" },
  nodeCardFiveDescription: { title: "Generează acțiunile juridice recomandate și pașii următori" },
};

export default interactiveWorkflowDemo;
