// src/i18n/public/templates.ro.ts
import type { LanguageData } from "@/types/languageDataTypes";

const templates: LanguageData["public"]["templates"] = {
  templatesTitle: { title: "Șabloane de documente juridice" },
  templatesDescription: {
    title:
      "Răsfoiește și generează șabloane profesionale în diverse categorii.",
  },
  searchResultTitle: { title: "Rezultatele căutării pentru" },
  searchResultDescriptionFirstWord: { title: "Găsite" },
  searchResultDescriptionRestOfText: {
    title: "șabloane care se potrivesc cu căutarea ta",
  },
  actionBtnUseTemplate: { title: "Folosește șablonul" },
  templatesAvailableMsg: { title: "" },
  showLessBtn: { title: "Afișează mai puțin" },
  showMoreFirstBtn: { title: "Afișează" },
  showMoreLastBtn: { title: "mai mult" },
  moreCategoriesFirstBtn: { title: "Afișează" },
  moreCategoriesLastBtn: { title: "mai multe categorii" },
  noSearchResultsTitle: {
    title: "Nu au fost găsite șabloane care să corespundă cu",
  },
  useTemplateBtn: { title: "Folosește" },

  categories: {
    "Sales Documents and Forms": {
      title: "Documente și formulare de vânzări",
      iconKey: "FileText",
      templates: [
        { title: "Contract de vânzare (bunuri)" },
        { title: "Contract de vânzare (servicii)" },
        { title: "Formular de comandă" },
        { title: "Ofertă comercială / cotație" },
        { title: "Comandă de achiziție (Purchase Order)" },
        { title: "Confirmare de comandă" },
        { title: "Acord privind comisionul de vânzări" },
        { title: "Acord de reseller" },
        { title: "Acord de distribuție" },
        { title: "Formular cerere de credit" },
        { title: "Autorizație de returnare marfă (RMA)" },
        { title: "Declarație de garanție" },
        { title: "Termeni și condiții de vânzare" },
        { title: "Factură" },
        { title: "Chitanță de vânzare" },
      ],
    },
    "Policy and Compliance Documents": {
      title: "Politici și documente de conformitate",
      iconKey: "Shield",
      templates: [
        { title: "Cod de conduită" },
        { title: "Politică anti-mită și anti-corupție" },
        { title: "Politica avertizorului de integritate" },
        { title: "Politica privind conflictul de interese" },
        { title: "Politica de securitate a informațiilor" },
        { title: "Politica de utilizare acceptabilă" },
        { title: "Politica de păstrare a datelor" },
        { title: "Politica BYOD (Bring Your Own Device)" },
        { title: "Politica privind sancțiunile și controalele la export" },
        { title: "Politica de sănătate și securitate" },
        { title: "Politica ESG / de sustenabilitate" },
        { title: "Politica AML / KYC" },
      ],
    },
    "Letters and Notices Templates": {
      title: "Modele de scrisori și notificări",
      iconKey: "Mail",
      templates: [
        { title: "Notificare de plată (somație)" },
        { title: "Notificare de încetare și renunțare (Cease & Desist)" },
        { title: "Notificare de încălcare" },
        { title: "Notificare pentru plată întârziată" },
        { title: "Notificare de intenție de acționare în judecată" },
        { title: "Notificare de reziliere (contract)" },
        { title: "Notificare de cesiune" },
        { title: "Notificare de forță majoră" },
        { title: "Notificare de neprelungire" },
        { title: "Notificare de modificare a termenilor" },
        { title: "Notificare privind încălcarea confidențialității" },
        { title: "Scrisoare de bună stare" },
      ],
    },
    "Web & Technology Agreements": {
      title: "Acorduri Web & Tehnologie",
      iconKey: "Globe",
      templates: [
        { title: "Contract de abonament SaaS" },
        { title: "Contract de licență software" },
        { title: "Contract de mentenanță și suport" },
        { title: "Contract de licență API" },
        { title: "Acord de testare beta" },
        { title: "Acord de licență cu utilizatorul final (EULA)" },
        { title: "Contract de servicii cloud" },
        { title: "Contract de servicii profesionale (tech)" },
        { title: "Acord de nivel de serviciu (SLA) / disponibilitate" },
        { title: "Acord de escrow pentru cod sursă" },
        { title: "Acord de evaluare a tehnologiei" },
        { title: "Termeni de utilizare ai site-ului" },
      ],
    },
    "Proposal Templates": {
      title: "Modele de propuneri",
      iconKey: "Presentation",
      templates: [
        { title: "Propunere de afaceri" },
        { title: "Propunere de vânzare" },
        { title: "Propunere de proiect" },
        { title: "Răspuns la RFP" },
        { title: "Ofertă de licitație" },
        { title: "Propunere de grant" },
        { title: "Propunere de sponsorizare" },
        { title: "Propunere de marketing" },
        { title: "Propunere de consultanță" },
        { title: "Declarație de lucrări (SOW) – propunere" },
        { title: "Propunere de buget" },
        { title: "Propunere de parteneriat" },
      ],
    },
    "Financial Agreements": {
      title: "Acorduri financiare",
      iconKey: "DollarSign",
      templates: [
        { title: "Contract de împrumut (garantat)" },
        { title: "Contract de împrumut (negarantat)" },
        { title: "Bilet la ordin (Promissory Note)" },
        { title: "Contract pentru linie de credit" },
        { title: "Acord de garanție personală (Guaranty)" },
        { title: "Acord de garanție (Security Agreement)" },
        { title: "Acord intercreditori" },
        { title: "Acord de escrow" },
        { title: "Acord de partajare a veniturilor" },
        { title: "Acord de redevențe" },
        { title: "Acord de eșalonare a plății" },
        { title: "Acord de amânare (Forbearance)" },
      ],
    },
    "Family Law": {
      title: "Dreptul familiei",
      iconKey: "Heart",
      templates: [
        { title: "Acord prenupțial" },
        { title: "Acord postnupțial" },
        { title: "Acord de separare" },
        { title: "Acord de divorț (tranzacție)" },
        { title: "Plan parental" },
        { title: "Acord privind custodia copilului" },
        { title: "Acord privind pensia de întreținere" },
        { title: "Acord privind sprijinul soțului/soției" },
        { title: "Acord de coabitare" },
        { title: "Acord de adopție" },
        { title: "Acord de surogație" },
        { title: "Cerere de schimbare a numelui" },
      ],
    },
    "Employment Legal Templates": {
      title: "Modele juridice pentru angajare",
      iconKey: "Briefcase",
      templates: [
        { title: "Scrisoare de ofertă de angajare" },
        { title: "Contract de muncă (normă întreagă)" },
        { title: "Contract de muncă (part-time)" },
        { title: "Contract de muncă doar pe comision" },
        { title: "Contract de prestări servicii (PFA/contractor)" },
        { title: "Acord de internship" },
        { title: "Acord de neconcurență" },
        { title: "Acord de non-solicitare" },
        { title: "NDA pentru angajați" },
        { title: "Confirmare primire regulament (Employee Handbook)" },
        { title: "Acord de muncă la distanță" },
        { title: "Acord de încetare și despăgubire" },
        { title: "Plan de îmbunătățire a performanței (PIP)" },
        { title: "Avertisment scris" },
      ],
    },
    "Real Estate": {
      title: "Imobiliare",
      iconKey: "Home",
      templates: [
        { title: "Contract de vânzare imobiliară (rezidențial)" },
        { title: "Contract de vânzare imobiliară (commercial)" },
        { title: "Ofertă de cumpărare imobil" },
        { title: "Act de vânzare (imobil)" },
        { title: "Declarație de renunțare la pretenții (Quitclaim Deed)" },
        { title: "Act de garanție (Warranty Deed)" },
        { title: "Contract de teren (Contract for Deed)" },
        { title: "Acord de servitute" },
        { title: "Drept de preempțiune" },
        { title: "Opțiune de cumpărare imobil" },
        { title: "Certificat de estoppel" },
        { title: "Act adițional imobiliar" },
      ],
    },
    "B2B Legal Documents": {
      title: "Documente juridice B2B",
      iconKey: "Building2",
      templates: [
        { title: "Acord-cadru de servicii (MSA)" },
        { title: "Fișă de lucru / Statement of Work (SOW)" },
        { title: "Acord-cadru de achiziții" },
        { title: "Acord cu furnizorul" },
        { title: "Acord cu partenerul de canal" },
        { title: "Acord de distribuție" },
        { title: "Acord OEM" },
        { title: "Acord de joint venture" },
        { title: "Acord de teaming" },
        { title: "Acord de recomandare" },
        { title: "Acord de colaborare" },
        { title: "Acord de nivel de serviciu (SLA)" },
      ],
    },
    "Business Document": {
      title: "Documente de afaceri",
      iconKey: "FileCheck",
      templates: [
        { title: "Statut (Bylaws)" },
        { title: "Acord de funcționare LLC (Operating Agreement)" },
        { title: "Acordul acționarilor" },
        { title: "Acordul fondatorilor" },
        { title: "Consimțământul consiliului" },
        { title: "Procese-verbale ale ședinței" },
        { title: "Hotărâre corporativă" },
        { title: "Scrisoare de autorizare corporativă" },
        { title: "Certificatul secretarului" },
        { title: "Împuternicire pentru agentul înregistrat" },
      ],
    },
    "Last Will and Testament": {
      title: "Testament și ultime dispoziții",
      iconKey: "Crown",
      templates: [
        { title: "Testament simplu" },
        { title: "Testament cu transfer în trust (Pour-Over)" },
        { title: "Testament comun (soți)" },
        { title: "Anexă la testament (Living Will Addendum)" },
        { title: "Codicil la testament" },
        { title: "Schiță de testament olograf" },
      ],
    },
    "Bill of Sale": {
      title: "Contract de vânzare-cumpărare (Bill of Sale)",
      iconKey: "FileText",
      templates: [
        { title: "Bill of Sale general" },
        { title: "Bill of Sale autoturism" },
        { title: "Bill of Sale ambarcațiune" },
        { title: "Bill of Sale motocicletă" },
        { title: "Bill of Sale remorcă" },
        { title: "Bill of Sale echipament" },
        { title: "Bill of Sale aeronave" },
        { title: "Bill of Sale active de afaceri" },
        { title: "Bill of Sale casă mobilă" },
        { title: "Bill of Sale animale" },
      ],
    },
    "Power of Attorney (POA)": {
      title: "Împuternicire (Power of Attorney)",
      iconKey: "Key",
      templates: [
        { title: "Procura generală" },
        { title: "Procura durabilă" },
        { title: "Procura limitată" },
        { title: "Procura medicală" },
        { title: "Procura financiară" },
        { title: "Procura pentru minor" },
        { title: "Procura pentru tranzacții imobiliare" },
        { title: "Procura pentru vehicul" },
        { title: "Procura condiționată (Springing)" },
        { title: "Revocarea procurii" },
      ],
    },
    "Eviction Notice": {
      title: "Notificări de evacuare",
      iconKey: "AlertTriangle",
      templates: [
        { title: "Notificare plătește sau părăsește" },
        { title: "Notificare remediază sau părăsește" },
        { title: "Notificare necondiționată de părăsire" },
        { title: "Notificare de încetare (neplată)" },
        { title: "Notificare de 30 de zile pentru eliberare" },
        { title: "Notificare de 60 de zile pentru eliberare" },
        { title: "Notificare încălcare contract de închiriere" },
        { title: "Notificare de reziliere pentru cauză" },
        { title: "Notificare de reziliere fără cauză" },
        { title: "Notificare chiriaș rămas peste termen" },
      ],
    },
    "NDA (Non-Disclosure Agreements)": {
      title: "Acorduri de confidențialitate (NDA)",
      iconKey: "Lock",
      templates: [
        { title: "NDA unilateral" },
        { title: "NDA bilateral (mutual)" },
        { title: "NDA multilateral" },
        { title: "NDA pentru angajați" },
        { title: "NDA pentru contractori" },
        { title: "NDA pentru investitori" },
        { title: "NDA pentru M&A" },
        { title: "NDA pentru evaluarea produsului" },
        { title: "NDA avocat–client" },
        { title: "NDA unilateral cu clauză de non-solicitare" },
      ],
    },
    "Lease Agreement": {
      title: "Contracte de închiriere / locațiune",
      iconKey: "Home",
      templates: [
        { title: "Contract de închiriere (rezidențial)" },
        { title: "Contract de închiriere (commercial)" },
        { title: "Contract de închiriere lună-la-lună" },
        { title: "Acord între colegi de cameră" },
        { title: "Contract de subînchiriere" },
        { title: "Acord de reînnoire a chiriei" },
        { title: "Acord de prelungire a chiriei" },
        { title: "Acord de cesiune a chiriei" },
        { title: "Contract de închiriere pe termen scurt" },
        { title: "Contract de închiriere spațiu de birouri" },
        { title: "Contract de leasing echipamente" },
        { title: "Contract de leasing auto" },
      ],
    },
    "Corporate Formation & Governance": {
      title: "Constituire și guvernanță corporativă",
      iconKey: "Building2",
      templates: [
        { title: "Act constitutiv (Articles of Incorporation)" },
        { title: "Act de organizare (LLC)" },
        { title: "Consimțământ inițial al consiliului" },
        { title: "Statut (Bylaws)" },
        { title: "Acord de funcționare LLC" },
        { title: "Acordul acționarilor" },
        { title: "Acordul fondatorilor" },
        { title: "Hotărâre de numire a ofițerilor" },
        { title: "Scrisoare de autorizare pentru EIN" },
        { title: "Consimțământ scris în loc de ședință" },
      ],
    },
    "Startups & Fundraising": {
      title: "Startup-uri și finanțare",
      iconKey: "TrendingUp",
      templates: [
        { title: "Acord de colaborare între fondatori" },
        { title: "Acord de advisor" },
        { title: "Plan de stimulente în acțiuni (Equity Plan)" },
        { title: "Contract de cumpărare acțiuni restricționate" },
        { title: "Notificare de acordare opțiuni pe acțiuni" },
        { title: "Scrisoare pentru opțiunea 83(b)" },
        { title: "Side letter de prorata" },
        { title: "Acord pentru observator în consiliu" },
        { title: "SAFE (pre-money)" },
        { title: "SAFE (post-money)" },
      ],
    },
    "Investment & Securities": {
      title: "Investiții și valori mobiliare",
      iconKey: "PiggyBank",
      templates: [
        { title: "Notă convertibilă (Convertible Note)" },
        { title: "Acord de cumpărare acțiuni" },
        { title: "Acord de subscriere" },
        { title: "Acord privind drepturile investitorilor" },
        { title: "Acord de vot" },
        { title: "Acord ROFR & Co-Sale" },
        { title: "Term sheet" },
        { title: "Acord de warrant" },
        { title: "Acord de vânzare secundară" },
        { title: "Șablon tabel de capitalizare" },
      ],
    },
    "M&A / Corporate Transactions": {
      title: "M&A / Tranzacții corporative",
      iconKey: "Users",
      templates: [
        { title: "Contract de achiziție de active" },
        { title: "Contract de achiziție de acțiuni (M&A)" },
        { title: "Acord de fuziune" },
        { title: "Scrisoare de intenție (M&A)" },
        { title: "Acord de confidențialitate (Deal NDA)" },
        { title: "Acord de servicii de tranziție" },
        { title: "Bill of Sale (active de afaceri)" },
        { title: "Acord de cesiune și asumare" },
        { title: "Șablon pentru dezvăluiri (Disclosure Schedules)" },
        { title: "Listă de verificare pentru închidere" },
      ],
    },
    "Banking & Lending": {
      title: "Bancar și creditare",
      iconKey: "CreditCard",
      templates: [
        { title: "Contract pentru servicii de plăți comerciale" },
        { title: "Formular de autorizare ACH" },
        { title: "Acord pentru procesarea plăților cu cardul" },
        { title: "Acord de factoring" },
        { title: "Acord de finanțare a facturilor" },
        { title: "Acord de gaj (Pledge Agreement)" },
        { title: "Acord de subordonare" },
        { title: "Acord pentru facilitate de credit" },
        { title: "Cerere pentru scrisoare de credit" },
        { title: "Formular UCC-1 (înregistrare garanție)" },
      ],
    },
    Insurance: {
      title: "Asigurări",
      iconKey: "Umbrella",
      templates: [
        { title: "Anexă cu cerințe de asigurare" },
        { title: "Acord de despăgubire și exonerare" },
        { title: "Acord privind renunțarea la subrogare" },
        { title: "Cerere pentru certificat de asigurare" },
        {
          title:
            "Scrisoare pentru desemnarea beneficiarului plății (Loss Payee)",
        },
        { title: "Scrisoare către brokerul de asigurări" },
        { title: "Notificare privind întreruperea afacerii" },
        { title: "Endorsament la polița de asigurare" },
        { title: "Scrisoare de notificare a daunelor" },
        { title: "Acord de transfer al riscului" },
      ],
    },
    "Privacy & Data Protection": {
      title: "Confidențialitate și protecția datelor",
      iconKey: "Eye",
      templates: [
        { title: "Politică de confidențialitate" },
        { title: "Politică privind cookie-urile" },
        { title: "Acord de prelucrare a datelor (DPA)" },
        { title: "Anexă cu clauze contractuale standard" },
        { title: "Evaluare de impact asupra protecției datelor (DPIA)" },
        { title: "Registrul activităților de prelucrare (ROPA)" },
        { title: "Răspuns la cerere de acces a persoanei vizate" },
        { title: "Politică de notificare a încălcării datelor" },
        { title: "Acord de partajare a datelor" },
        { title: "Acord operator–persoană împuternicită" },
        { title: "Evaluarea impactului transferului (TIA)" },
      ],
    },
    "Intellectual Property": {
      title: "Proprietate intelectuală",
      iconKey: "Lightbulb",
      templates: [
        { title: "Acord de cesiune a drepturilor de proprietate intelectuală" },
        { title: "Acord de cesiune a invențiilor" },
        { title: "Contract de licență de autor" },
        { title: "Contract de licență de marcă" },
        { title: "Contract de licență de brevet" },
        { title: "Acord de dezvoltare în comun" },
        { title: "Acord de transfer de tehnologie" },
        { title: "Acord de „work made for hire”" },
        { title: "Renunțare la drepturile morale" },
        { title: "Notificare de retragere DMCA" },
      ],
    },
    "AI & Data Science Agreements": {
      title: "Acorduri pentru AI și știința datelor",
      iconKey: "Laptop",
      templates: [
        { title: "Contract de servicii AI" },
        { title: "Acord de dezvoltare de modele" },
        { title: "Acord de utilizare a datelor" },
        { title: "Licență pentru seturi de date ML" },
        { title: "Acord de găzduire a modelului" },
        { title: "Contract pentru prompt engineering" },
        { title: "Acord de evaluare a modelului" },
        { title: "Acord pentru generarea de date sintetice" },
        { title: "Politică de utilizare responsabilă a AI" },
        { title: "Anexă de utilizare acceptabilă pentru AI" },
      ],
    },
    "Marketing & Advertising": {
      title: "Marketing și publicitate",
      iconKey: "Palette",
      templates: [
        { title: "Contract de servicii de marketing" },
        { title: "Contract cu influencer" },
        { title: "Acord pentru program de afiliere" },
        { title: "Acord de sponsorizare" },
        { title: "Ordin de inserție publicitară" },
        { title: "Formular de eliberare a drepturilor (talent release)" },
        { title: "Acord de mărturie și folosire a imaginii" },
        { title: "Acord de co-marketing" },
        { title: "Regulament oficial pentru tombole" },
        { title: "Acord de ambasador de brand" },
      ],
    },
    "Freelancer & Creator Agreements": {
      title: "Acorduri pentru freelanceri și creatori",
      iconKey: "Camera",
      templates: [
        { title: "Contract de servicii freelancer" },
        { title: "Contract de servicii creative" },
        { title: "Contract de fotografie" },
        { title: "Contract de work-for-hire" },
        { title: "Contract de design grafic" },
        { title: "Contract de voice-over" },
        { title: "Acord de licențiere de conținut" },
        { title: "Acord pentru invitat de podcast" },
        { title: "Contract de licență muzicală" },
        { title: "Licență pentru material video de stoc" },
      ],
    },
    "Property Management": {
      title: "Administrare proprietăți",
      iconKey: "Home",
      templates: [
        { title: "Contract de administrare a proprietății" },
        { title: "Formular de preluare chiriaș" },
        { title: "Listă de verificare mutare-în / mutare-out" },
        { title: "Anexă pentru animale de companie" },
        { title: "Plan de plată întârziată a chiriei" },
        { title: "Notificare de acces în proprietate" },
        { title: "Notificare de majorare a chiriei" },
        { title: "Notificare de neprelungire" },
        { title: "Chitanță pentru depozitul de garanție" },
        { title: "Scrisoare de returnare a depozitului" },
      ],
    },
    "Construction & Contractor": {
      title: "Construcții și contractori",
      iconKey: "Wrench",
      templates: [
        { title: "Contract de construcție (preț fix)" },
        { title: "Contract de construcție (timp și materiale)" },
        { title: "Contract de antreprenor independent (meșteșuguri)" },
        { title: "Contract de subcontractare" },
        { title: "Ordin de modificare (Change Order)" },
        { title: "Renunțare și descărcare de garanții (Lien Waiver)" },
        { title: "Șablon pentru garanție de bună execuție" },
        { title: "Șablon pentru garanție de plată" },
        { title: "Șablon listă de remedieri (Punch List)" },
        { title: "Garanție pentru calitatea lucrărilor" },
      ],
    },
    "Manufacturing & Supply Chain": {
      title: "Producție și lanț de aprovizionare",
      iconKey: "Factory",
      templates: [
        { title: "Contract de servicii de producție" },
        { title: "Acord de furnizare (Supply Agreement)" },
        { title: "Acord de calitate" },
        { title: "Termeni și condiții pentru comenzi de achiziție" },
        { title: "Acord de consignație" },
        { title: "Acord privind proprietatea asupra sculelor (Tooling)" },
        { title: "Garanție pentru produse finite" },
        { title: "Acord de ambalare și etichetare" },
        { title: "Acord VMI (stoc administrat de furnizor)" },
        { title: "Șablon raport de neconformitate" },
      ],
    },
    "Transportation & Logistics": {
      title: "Transport și logistică",
      iconKey: "Truck",
      templates: [
        { title: "Contract de servicii de transport" },
        { title: "Acord de brokeraj de marfă" },
        { title: "Scrisoare de trăsură (Bill of Lading)" },
        { title: "Termeni și condiții de expediere" },
        { title: "Contract de servicii depozitare" },
        { title: "Acord 3PL" },
        { title: "Acord cu transportatorul" },
        { title: "Contract de livrare" },
        { title: "Politică de utilizare a flotei auto" },
        { title: "Acord de confidențialitate în lanțul de aprovizionare" },
      ],
    },
    "Retail & eCommerce": {
      title: "Retail și eCommerce",
      iconKey: "Store",
      templates: [
        { title: "Termeni și condiții eCommerce" },
        { title: "Politică de retur și rambursare" },
        { title: "Acord pentru vânzători pe marketplace" },
        { title: "Acord de dropshipping" },
        { title: "Termeni pentru carduri cadou" },
        { title: "Termeni pentru cutii de abonament" },
        { title: "Licență pentru conținut generat de utilizatori" },
        { title: "Consimțământ SMS pentru marketing" },
        { title: "Politică de aliniere a prețului (Price Match)" },
        { title: "Termeni BOPIS (Buy Online, Pick Up In Store)" },
      ],
    },
    "Hospitality & Events": {
      title: "Hospitality & evenimente",
      iconKey: "Plane",
      templates: [
        { title: "Contract de închiriere locație" },
        { title: "Contract de catering" },
        { title: "Contract de servicii pentru evenimente" },
        { title: "Acord cu furnizorul de eveniment" },
        { title: "Contract cu speaker" },
        { title: "Contract pentru servicii de DJ" },
        { title: "Contract de fotografie pentru nuntă" },
        { title: "Acord de sponsorizare pentru conferință" },
        { title: "Termeni și condiții de ticketing" },
        { title: "Declarație de răspundere pentru evenimente" },
      ],
    },
    "Environmental & Energy": {
      title: "Mediu și energie",
      iconKey: "TreePine",
      templates: [
        { title: "Politică de conformitate de mediu" },
        { title: "Acord de despăgubire de mediu" },
        { title: "Acord de eliminare a deșeurilor" },
        { title: "Acord de reciclare" },
        { title: "PPA energie regenerabilă" },
        { title: "Contract de servicii energetice" },
        { title: "Acord de cumpărare a creditelor de carbon" },
        { title: "Listă de verificare pentru due diligence de mediu" },
        { title: "Plan de prevenire și răspuns la scurgeri" },
        { title: "Acord pentru manipularea substanțelor periculoase" },
      ],
    },
    "Agriculture & Food": {
      title: "Agricultură și industrie alimentară",
      iconKey: "Wheat",
      templates: [
        { title: "Contract de arendă agricolă" },
        { title: "Acord de împărțire a recoltei (Crop Share)" },
        { title: "Acord de cumpărare animale" },
        { title: "Acord de furnizare produse alimentare" },
        { title: "Acord de co-ambalare (Co-Packing)" },
        { title: "Șablon plan de siguranță alimentară" },
        { title: "Declarație pentru certificare ecologică" },
        { title: "Acord de membru CSA" },
        { title: "Contract de servicii agricole" },
        { title: "Acord de acoperire cu instrumente derivate pe mărfuri" },
      ],
    },
    "Government & Public Sector": {
      title: "Guvern și sector public",
      iconKey: "MapPin",
      templates: [
        { title: "Contract de achiziții publice" },
        { title: "Declarație de necoluziune" },
        { title: "Politică de conformitate privind lobby-ul" },
        { title: "Cerere FOIA (acces la informații)" },
        { title: "Declarație privind drepturile asupra datelor" },
        { title: "Listă de verificare pentru înregistrare SAM" },
        { title: "Certificat de neexcludere (Debarment)" },
        { title: "Acord parteneriat public-privat" },
        { title: "Șablon raport de conformitate pentru grant" },
        { title: "Matrice de conformitate la RFP" },
      ],
    },
    "Court Forms & Litigation": {
      title: "Formulare judiciare și litigii",
      iconKey: "Gavel",
      templates: [
        { title: "Cerere de chemare în judecată" },
        { title: "Întâmpinare" },
        { title: "Cerere de respingere" },
        { title: "Cerere de judecată sumară" },
        { title: "Declarație pe propria răspundere (afidavit)" },
        { title: "Subpoena (citație)" },
        { title: "Notificare de reprezentare" },
        { title: "Notificare de păstrare a documentelor (Litigation Hold)" },
        { title: "Acord de tranzacție" },
        { title: "Descărcare reciprocă de pretenții" },
        { title: "Ordin de consimțământ" },
        { title: "Acord de mediere" },
      ],
    },
    "Estate Planning (Broad)": {
      title: "Planificare succesorală (general)",
      iconKey: "Crown",
      templates: [
        { title: "Testament (Last Will and Testament)" },
        { title: "Directive anticipate (Living Will)" },
        { title: "Trust revocabil" },
        { title: "Trust irevocabil" },
        { title: "Procura durabilă" },
        { title: "Procura medicală" },
        { title: "Autorizare HIPAA" },
        { title: "Ordin de ne-resuscitare (DNR)" },
        { title: "Transfer prin act la deces (TOD)" },
        { title: "Formular de desemnare a beneficiarului" },
      ],
    },
    "Cybersecurity & Incident Response": {
      title: "Securitate cibernetică și răspuns la incidente",
      iconKey: "ShieldIcon",
      templates: [
        { title: "Plan de răspuns la incidente" },
        { title: "Formular raport incident de securitate" },
        { title: "Politică de notificare a încălcării datelor" },
        { title: "Politică de dezvăluire a vulnerabilităților" },
        { title: "Politică de control al accesului" },
        { title: "Chestionar de securitate pentru terți" },
        { title: "Reguli de desfășurare pentru testarea de penetrare" },
        { title: "Anexă de securitate a informațiilor" },
        { title: "Plan de continuitate și recuperare în caz de dezastru" },
        { title: "Politică de management al cheilor" },
      ],
    },
  },
};

export default templates;
