const interactiveWorkflowDemo = {
    nodeTitle: { title: "Node Palette" },
    nodeOneTitle: { title: "Document Handling" },
    runBtn: { title: "Run Workflow" },
    saveBtn: { title: "Save" },
    shareBtn: { title: "Share" },
    nodeOneOptionOneTitle: { title: "Upload Contract" },
    nodeOneOptionOneDescription: { title: "Upload rental agreement" },
    nodeOneOptionTwoTitle: { title: "Analyze Contract" },
    nodeOneOptionTwoDescription: { title: "Extract contract terms" },
    nodeTwoTitle: { title: "Legal Research" },
    nodeTwoOptionOneTitle: { title: "Research Rights" },
    nodeTwoOptionOneDescription: { title: "Research tenant protections" },
    nodeTwoOptionTwoTitle: { title: "Classify Dispute" },
    nodeTwoOptionTwoDescription: { title: "Categorize the dispute" },
    nodeThreeTitle: { title: "Strategy" },
    nodeThreeOptionOneTitle: { title: "Legal Strategy" },
    nodeThreeOptionOneDescription: { title: "Generate legal recommendations" },
    nodeCardOneTitle: { title: "Upload Rental Contract" },
    nodeCardOneDescription: { title: "Upload the rental contract" },
    nodeCardTwoTitle: { title: "Analyze Contract Terms" },
    nodeCardTwoDescription: { title: "Extract key clauses, terms and obligations" },
    nodeCardThreeTitle: { title: "Research Tenant Rights" },
    nodeCardThreeDescription: { title: "Research applicable tenant rights and protections" },
    nodeCardFourTitle: { title: "Classify Dispute Type" },
    nodeCardFourDescription: { title: "Categorize dispute type and severity level" },
    nodeCardFiveTitle: { title: "Legal Strategy" },
    nodeCardFiveDescription: { title: "Generate recommended legal actions and next steps" },
};

export default interactiveWorkflowDemo;
