// src/i18n/public/templates.ts
import type { LanguageData } from "@/types/languageDataTypes";

const templates: LanguageData["public"]["templates"] = {
  templatesTitle: { title: "Legal Document Templates" },
  templatesDescription: {
    title: "Browse and generate professional templates across categories.",
  },
  categories: {
    "Sales Documents and Forms": {
      title: "Sales Documents and Forms",
      iconKey: "FileText",
      templates: [
        { title: "Sales Contract (Goods)" },
        { title: "Sales Contract (Services)" },
        { title: "Sales Order Form" },
        { title: "Sales Quote / Quotation" },
        { title: "Purchase Order" },
        { title: "Order Confirmation" },
        { title: "Sales Commission Agreement" },
        { title: "Reseller Agreement" },
        { title: "Distributor Agreement" },
        { title: "Credit Application Form" },
        { title: "Return Merchandise Authorization (RMA)" },
        { title: "Warranty Statement" },
        { title: "Terms and Conditions of Sale" },
        { title: "Invoice" },
        { title: "Sales Receipt" },
      ],
    },
    "Policy and Compliance Documents": {
      title: "Policy and Compliance Documents",
      iconKey: "Shield",
      templates: [
        { title: "Code of Conduct" },
        { title: "Anti-Bribery and Corruption Policy" },
        { title: "Whistleblower Policy" },
        { title: "Conflict of Interest Policy" },
        { title: "Information Security Policy" },
        { title: "Acceptable Use Policy" },
        { title: "Data Retention Policy" },
        { title: "BYOD Policy" },
        { title: "Sanctions & Export Controls Policy" },
        { title: "Health and Safety Policy" },
        { title: "ESG / Sustainability Policy" },
        { title: "AML / KYC Policy" },
      ],
    },
    "Letters and Notices Templates": {
      title: "Letters and Notices Templates",
      iconKey: "Mail",
      templates: [
        { title: "Demand Letter" },
        { title: "Cease and Desist Letter" },
        { title: "Notice of Breach" },
        { title: "Past Due Payment Letter" },
        { title: "Notice of Intent to Sue" },
        { title: "Termination Notice (Agreement)" },
        { title: "Notice of Assignment" },
        { title: "Force Majeure Notice" },
        { title: "Non-Renewal Notice" },
        { title: "Change of Terms Notice" },
        { title: "Confidentiality Breach Notice" },
        { title: "Letter of Good Standing" },
      ],
    },
    "Web & Technology Agreements": {
      title: "Web & Technology Agreements",
      iconKey: "Globe",
      templates: [
        { title: "SaaS Subscription Agreement" },
        { title: "Software License Agreement" },
        { title: "Maintenance & Support Agreement" },
        { title: "API License Agreement" },
        { title: "Beta Test Agreement" },
        { title: "EULA" },
        { title: "Cloud Services Agreement" },
        { title: "Professional Services Agreement (Tech)" },
        { title: "Uptime / Service Level Agreement (SLA)" },
        { title: "Source Code Escrow Agreement" },
        { title: "Technology Evaluation Agreement" },
        { title: "Website Terms of Use" },
      ],
    },
    "Proposal Templates": {
      title: "Proposal Templates",
      iconKey: "Presentation",
      templates: [
        { title: "Business Proposal" },
        { title: "Sales Proposal" },
        { title: "Project Proposal" },
        { title: "RFP Response" },
        { title: "Bid Proposal" },
        { title: "Grant Proposal" },
        { title: "Sponsorship Proposal" },
        { title: "Marketing Proposal" },
        { title: "Consulting Proposal" },
        { title: "Statement of Work (Proposal)" },
        { title: "Budget Proposal" },
        { title: "Partnership Proposal" },
      ],
    },
    "Financial Agreements": {
      title: "Financial Agreements",
      iconKey: "DollarSign",
      templates: [
        { title: "Loan Agreement (Secured)" },
        { title: "Loan Agreement (Unsecured)" },
        { title: "Promissory Note" },
        { title: "Line of Credit Agreement" },
        { title: "Guaranty Agreement" },
        { title: "Security Agreement" },
        { title: "Intercreditor Agreement" },
        { title: "Escrow Agreement" },
        { title: "Revenue Share Agreement" },
        { title: "Royalty Agreement" },
        { title: "Payment Plan Agreement" },
        { title: "Forbearance Agreement" },
      ],
    },
    "Family Law": {
      title: "Family Law",
      iconKey: "Heart",
      templates: [
        { title: "Prenuptial Agreement" },
        { title: "Postnuptial Agreement" },
        { title: "Separation Agreement" },
        { title: "Divorce Settlement Agreement" },
        { title: "Parenting Plan" },
        { title: "Child Custody Agreement" },
        { title: "Child Support Agreement" },
        { title: "Spousal Support Agreement" },
        { title: "Cohabitation Agreement" },
        { title: "Adoption Agreement" },
        { title: "Surrogacy Agreement" },
        { title: "Name Change Petition" },
      ],
    },
    "Employment Legal Templates": {
      title: "Employment Legal Templates",
      iconKey: "Briefcase",
      templates: [
        { title: "Employment Offer Letter" },
        { title: "Employment Agreement (Full-Time)" },
        { title: "Employment Agreement (Part-Time)" },
        { title: "Commission-Only Employment Agreement" },
        { title: "Independent Contractor Agreement" },
        { title: "Internship Agreement" },
        { title: "Non-Compete Agreement" },
        { title: "Non-Solicitation Agreement" },
        { title: "Employee NDA" },
        { title: "Employee Handbook Acknowledgment" },
        { title: "Remote Work Agreement" },
        { title: "Separation and Release Agreement" },
        { title: "Performance Improvement Plan (PIP)" },
        { title: "Written Warning Notice" },
      ],
    },
    "Real Estate": {
      title: "Real Estate",
      iconKey: "Home",
      templates: [
        { title: "Real Estate Purchase Agreement (Residential)" },
        { title: "Real Estate Purchase Agreement (Commercial)" },
        { title: "Offer to Purchase Real Estate" },
        { title: "Deed of Sale (Real Property)" },
        { title: "Quitclaim Deed" },
        { title: "Warranty Deed" },
        { title: "Land Contract (Contract for Deed)" },
        { title: "Easement Agreement" },
        { title: "Right of First Refusal Agreement" },
        { title: "Option to Purchase Real Estate" },
        { title: "Estoppel Certificate" },
        { title: "Real Estate Addendum" },
      ],
    },
    "B2B Legal Documents": {
      title: "B2B Legal Documents",
      iconKey: "Building2",
      templates: [
        { title: "Master Services Agreement (MSA)" },
        { title: "Statement of Work (SOW)" },
        { title: "Master Purchase Agreement" },
        { title: "Supplier Agreement" },
        { title: "Channel Partner Agreement" },
        { title: "Distribution Agreement" },
        { title: "OEM Agreement" },
        { title: "Joint Venture Agreement" },
        { title: "Teaming Agreement" },
        { title: "Referral Agreement" },
        { title: "Collaboration Agreement" },
        { title: "Service Level Agreement (SLA)" },
      ],
    },
    "Business Document": {
      title: "Business Document",
      iconKey: "FileCheck",
      templates: [
        { title: "Company Bylaws" },
        { title: "LLC Operating Agreement" },
        { title: "Shareholders' Agreement" },
        { title: "Founders' Agreement" },
        { title: "Board Consent" },
        { title: "Meeting Minutes" },
        { title: "Corporate Resolution" },
        { title: "Corporate Authorization Letter" },
        { title: "Secretary's Certificate" },
        { title: "Registered Agent Authorization" },
      ],
    },
    "Last Will and Testament": {
      title: "Last Will and Testament",
      iconKey: "Crown",
      templates: [
        { title: "Simple Will" },
        { title: "Pour-Over Will" },
        { title: "Joint Will (Spouses)" },
        { title: "Living Will Addendum" },
        { title: "Codicil to Will" },
        { title: "Holographic Will Outline" },
      ],
    },
    "Bill of Sale": {
      title: "Bill of Sale",
      iconKey: "FileText",
      templates: [
        { title: "General Bill of Sale" },
        { title: "Vehicle Bill of Sale" },
        { title: "Boat Bill of Sale" },
        { title: "Motorcycle Bill of Sale" },
        { title: "Trailer Bill of Sale" },
        { title: "Equipment Bill of Sale" },
        { title: "Aircraft Bill of Sale" },
        { title: "Business Asset Bill of Sale" },
        { title: "Mobile Home Bill of Sale" },
        { title: "Livestock Bill of Sale" },
      ],
    },
    "Power of Attorney (POA)": {
      title: "Power of Attorney (POA)",
      iconKey: "Key",
      templates: [
        { title: "General Power of Attorney" },
        { title: "Durable Power of Attorney" },
        { title: "Limited Power of Attorney" },
        { title: "Medical Power of Attorney" },
        { title: "Financial Power of Attorney" },
        { title: "Minor Child Power of Attorney" },
        { title: "Real Estate Power of Attorney" },
        { title: "Vehicle Power of Attorney" },
        { title: "Springing Power of Attorney" },
        { title: "Revocation of Power of Attorney" },
      ],
    },
    "Eviction Notice": {
      title: "Eviction Notice",
      iconKey: "AlertTriangle",
      templates: [
        { title: "Pay Rent or Quit Notice" },
        { title: "Cure or Quit Notice" },
        { title: "Unconditional Quit Notice" },
        { title: "Notice to Quit (Nonpayment)" },
        { title: "30-Day Notice to Vacate" },
        { title: "60-Day Notice to Vacate" },
        { title: "Lease Violation Notice" },
        { title: "Termination for Cause Notice" },
        { title: "Termination Without Cause Notice" },
        { title: "Holdover Tenant Notice" },
      ],
    },
    "NDA (Non-Disclosure Agreements)": {
      title: "NDA (Non-Disclosure Agreements)",
      iconKey: "Lock",
      templates: [
        { title: "Unilateral NDA" },
        { title: "Mutual NDA" },
        { title: "Multilateral NDA" },
        { title: "Employee NDA" },
        { title: "Contractor NDA" },
        { title: "Investor NDA" },
        { title: "M&A NDA" },
        { title: "Product Evaluation NDA" },
        { title: "Attorney–Client NDA" },
        { title: "One-Way NDA with No-Solicit" },
      ],
    },
    "Lease Agreement": {
      title: "Lease Agreement",
      iconKey: "Home",
      templates: [
        { title: "Residential Lease Agreement" },
        { title: "Commercial Lease Agreement" },
        { title: "Month-to-Month Rental Agreement" },
        { title: "Roommate Agreement" },
        { title: "Sublease Agreement" },
        { title: "Lease Renewal Agreement" },
        { title: "Lease Extension Agreement" },
        { title: "Lease Assignment Agreement" },
        { title: "Short-Term Rental Agreement" },
        { title: "Office Space Lease Agreement" },
        { title: "Equipment Lease Agreement" },
        { title: "Vehicle Lease Agreement" },
      ],
    },
    "Corporate Formation & Governance": {
      title: "Corporate Formation & Governance",
      iconKey: "Building2",
      templates: [
        { title: "Articles of Incorporation" },
        { title: "Articles of Organization (LLC)" },
        { title: "Initial Board Consent" },
        { title: "Bylaws" },
        { title: "LLC Operating Agreement" },
        { title: "Shareholders' Agreement" },
        { title: "Founders' Agreement" },
        { title: "Officer Appointment Resolution" },
        { title: "EIN Authorization Letter" },
        { title: "Written Consent in Lieu of Meeting" },
      ],
    },
    "Startups & Fundraising": {
      title: "Startups & Fundraising",
      iconKey: "TrendingUp",
      templates: [
        { title: "Founder Collaboration Agreement" },
        { title: "Advisor Agreement" },
        { title: "Equity Incentive Plan" },
        { title: "Restricted Stock Purchase Agreement" },
        { title: "Stock Option Grant Notice" },
        { title: "83(b) Election Letter" },
        { title: "Pro Rata Side Letter" },
        { title: "Board Observer Agreement" },
        { title: "SAFE (Pre-Money)" },
        { title: "SAFE (Post-Money)" },
      ],
    },
    "Investment & Securities": {
      title: "Investment & Securities",
      iconKey: "PiggyBank",
      templates: [
        { title: "Convertible Note" },
        { title: "Stock Purchase Agreement" },
        { title: "Subscription Agreement" },
        { title: "Investor Rights Agreement" },
        { title: "Voting Agreement" },
        { title: "ROFR & Co-Sale Agreement" },
        { title: "Term Sheet" },
        { title: "Warrant Agreement" },
        { title: "Secondary Sale Agreement" },
        { title: "Capitalization Table Template" },
      ],
    },
    "M&A / Corporate Transactions": {
      title: "M&A / Corporate Transactions",
      iconKey: "Users",
      templates: [
        { title: "Asset Purchase Agreement" },
        { title: "Stock Purchase Agreement (M&A)" },
        { title: "Merger Agreement" },
        { title: "Letter of Intent (M&A)" },
        { title: "Confidentiality Agreement (Deal NDA)" },
        { title: "Transition Services Agreement" },
        { title: "Bill of Sale (Business Assets)" },
        { title: "Assignment and Assumption Agreement" },
        { title: "Disclosure Schedules Template" },
        { title: "Closing Checklist" },
      ],
    },
    "Banking & Lending": {
      title: "Banking & Lending",
      iconKey: "CreditCard",
      templates: [
        { title: "Merchant Services Agreement" },
        { title: "ACH Authorization Form" },
        { title: "Credit Card Processing Agreement" },
        { title: "Factoring Agreement" },
        { title: "Invoice Financing Agreement" },
        { title: "Pledge Agreement" },
        { title: "Subordination Agreement" },
        { title: "Credit Facility Agreement" },
        { title: "Letter of Credit Application" },
        { title: "UCC-1 Financing Statement" },
      ],
    },
    Insurance: {
      title: "Insurance",
      iconKey: "Umbrella",
      templates: [
        { title: "Insurance Requirements Exhibit" },
        { title: "Hold Harmless and Indemnity Agreement" },
        { title: "Waiver of Subrogation Agreement" },
        { title: "Certificate of Insurance Request" },
        { title: "Loss Payee Endorsement Letter" },
        { title: "Broker of Record Letter" },
        { title: "Business Interruption Claim Notice" },
        { title: "Insurance Policy Endorsement" },
        { title: "Claims Notice Letter" },
        { title: "Risk Transfer Agreement" },
      ],
    },
    "Privacy & Data Protection": {
      title: "Privacy & Data Protection",
      iconKey: "Eye",
      templates: [
        { title: "Privacy Policy" },
        { title: "Cookie Policy" },
        { title: "Data Processing Agreement (DPA)" },
        { title: "Standard Contractual Clauses Addendum" },
        { title: "Data Protection Impact Assessment (DPIA)" },
        { title: "Records of Processing Activities (ROPA)" },
        { title: "Subject Access Request Response" },
        { title: "Data Breach Notification Letter" },
        { title: "Data Sharing Agreement" },
        { title: "Controller–Processor Agreement" },
        { title: "Transfer Impact Assessment" },
      ],
    },
    "Intellectual Property": {
      title: "Intellectual Property",
      iconKey: "Lightbulb",
      templates: [
        { title: "IP Assignment Agreement" },
        { title: "Invention Assignment Agreement" },
        { title: "Copyright License Agreement" },
        { title: "Trademark License Agreement" },
        { title: "Patent License Agreement" },
        { title: "Joint Development Agreement" },
        { title: "Technology Transfer Agreement" },
        { title: "Work Made for Hire Agreement" },
        { title: "Moral Rights Waiver" },
        { title: "DMCA Takedown Notice" },
      ],
    },
    "AI & Data Science Agreements": {
      title: "AI & Data Science Agreements",
      iconKey: "Laptop",
      templates: [
        { title: "AI Services Agreement" },
        { title: "Model Development Agreement" },
        { title: "Data Use Agreement" },
        { title: "ML Dataset License Agreement" },
        { title: "Model Hosting Agreement" },
        { title: "Prompt Engineering Services Agreement" },
        { title: "Model Evaluation Agreement" },
        { title: "Synthetic Data Generation Agreement" },
        { title: "Responsible AI Use Policy" },
        { title: "AI Acceptable Use Addendum" },
      ],
    },
    "Marketing & Advertising": {
      title: "Marketing & Advertising",
      iconKey: "Palette",
      templates: [
        { title: "Marketing Services Agreement" },
        { title: "Influencer Agreement" },
        { title: "Affiliate Program Agreement" },
        { title: "Sponsorship Agreement" },
        { title: "Advertising Insertion Order" },
        { title: "Talent Release Form" },
        { title: "Testimonial & Likeness Release" },
        { title: "Co-Marketing Agreement" },
        { title: "Sweepstakes Official Rules" },
        { title: "Brand Ambassador Agreement" },
      ],
    },
    "Freelancer & Creator Agreements": {
      title: "Freelancer & Creator Agreements",
      iconKey: "Camera",
      templates: [
        { title: "Freelance Services Agreement" },
        { title: "Creative Services Agreement" },
        { title: "Photography Services Agreement" },
        { title: "Work-for-Hire Agreement" },
        { title: "Graphic Design Agreement" },
        { title: "Voiceover Agreement" },
        { title: "Content Licensing Agreement" },
        { title: "Podcast Guest Release" },
        { title: "Music License Agreement" },
        { title: "Stock Footage License" },
      ],
    },
    "Property Management": {
      title: "Property Management",
      iconKey: "Home",
      templates: [
        { title: "Property Management Agreement" },
        { title: "Tenant Intake Form" },
        { title: "Move-In / Move-Out Checklist" },
        { title: "Pet Addendum" },
        { title: "Late Rent Payment Plan" },
        { title: "Notice of Entry" },
        { title: "Rent Increase Notice" },
        { title: "Notice of Non-Renewal" },
        { title: "Security Deposit Receipt" },
        { title: "Security Deposit Return Letter" },
      ],
    },
    "Construction & Contractor": {
      title: "Construction & Contractor",
      iconKey: "Wrench",
      templates: [
        { title: "Construction Contract (Fixed Price)" },
        { title: "Construction Contract (Time & Materials)" },
        { title: "Independent Contractor Agreement (Trades)" },
        { title: "Subcontractor Agreement" },
        { title: "Change Order" },
        { title: "Lien Waiver and Release" },
        { title: "Performance Bond Template" },
        { title: "Payment Bond Template" },
        { title: "Punch List Template" },
        { title: "Warranty of Workmanship" },
      ],
    },
    "Manufacturing & Supply Chain": {
      title: "Manufacturing & Supply Chain",
      iconKey: "Factory",
      templates: [
        { title: "Manufacturing Services Agreement" },
        { title: "Supply Agreement" },
        { title: "Quality Agreement" },
        { title: "Purchase Order Terms & Conditions" },
        { title: "Consignment Agreement" },
        { title: "Tooling Ownership Agreement" },
        { title: "Finished Goods Warranty" },
        { title: "Packaging & Labeling Agreement" },
        { title: "Vendor Managed Inventory Agreement" },
        { title: "Nonconformance Report Template" },
      ],
    },
    "Transportation & Logistics": {
      title: "Transportation & Logistics",
      iconKey: "Truck",
      templates: [
        { title: "Transportation Services Agreement" },
        { title: "Freight Broker Agreement" },
        { title: "Bill of Lading" },
        { title: "Shipping Terms and Conditions" },
        { title: "Warehouse Services Agreement" },
        { title: "3PL Agreement" },
        { title: "Carrier Agreement" },
        { title: "Delivery Service Agreement" },
        { title: "Fleet Vehicle Use Policy" },
        { title: "Supply Chain Confidentiality Agreement" },
      ],
    },
    "Retail & eCommerce": {
      title: "Retail & eCommerce",
      iconKey: "Store",
      templates: [
        { title: "eCommerce Terms and Conditions" },
        { title: "Return & Refund Policy" },
        { title: "Marketplace Seller Agreement" },
        { title: "Drop Shipping Agreement" },
        { title: "Gift Card Terms" },
        { title: "Subscription Box Terms" },
        { title: "User-Generated Content License" },
        { title: "SMS Marketing Consent Terms" },
        { title: "Price Match Policy" },
        { title: "BOPIS Terms" },
      ],
    },
    "Hospitality & Events": {
      title: "Hospitality & Events",
      iconKey: "Plane",
      templates: [
        { title: "Venue Rental Agreement" },
        { title: "Catering Services Agreement" },
        { title: "Event Services Agreement" },
        { title: "Event Vendor Agreement" },
        { title: "Speaker Agreement" },
        { title: "DJ Services Agreement" },
        { title: "Wedding Photography Contract" },
        { title: "Conference Sponsorship Agreement" },
        { title: "Ticketing Terms & Conditions" },
        { title: "Event Liability Waiver" },
      ],
    },
    "Environmental & Energy": {
      title: "Environmental & Energy",
      iconKey: "TreePine",
      templates: [
        { title: "Environmental Compliance Policy" },
        { title: "Environmental Indemnity Agreement" },
        { title: "Waste Disposal Agreement" },
        { title: "Recycling Services Agreement" },
        { title: "Renewable Energy PPA" },
        { title: "Energy Services Agreement" },
        { title: "Carbon Credit Purchase Agreement" },
        { title: "Environmental Due Diligence Checklist" },
        { title: "Spill Prevention & Response Plan" },
        { title: "Hazardous Materials Handling Agreement" },
      ],
    },
    "Agriculture & Food": {
      title: "Agriculture & Food",
      iconKey: "Wheat",
      templates: [
        { title: "Farm Lease Agreement" },
        { title: "Crop Share Agreement" },
        { title: "Livestock Purchase Agreement" },
        { title: "Food Supply Agreement" },
        { title: "Co-Packing Agreement" },
        { title: "Food Safety Plan Template" },
        { title: "Organic Certification Affidavit" },
        { title: "CSA Membership Agreement" },
        { title: "Agricultural Services Agreement" },
        { title: "Commodities Hedge Agreement" },
      ],
    },
    "Government & Public Sector": {
      title: "Government & Public Sector",
      iconKey: "MapPin",
      templates: [
        { title: "Government Contracting Agreement" },
        { title: "Non-Collusion Affidavit" },
        { title: "Lobbying Compliance Policy" },
        { title: "FOIA Request Letter" },
        { title: "Data Rights Assertion" },
        { title: "SAM Registration Checklist" },
        { title: "Debarment Certification" },
        { title: "Public-Private Partnership Agreement" },
        { title: "Grant Compliance Report Template" },
        { title: "RFP Compliance Matrix" },
      ],
    },
    "Court Forms & Litigation": {
      title: "Court Forms & Litigation",
      iconKey: "Gavel",
      templates: [
        { title: "Complaint" },
        { title: "Answer to Complaint" },
        { title: "Motion to Dismiss" },
        { title: "Motion for Summary Judgment" },
        { title: "Affidavit" },
        { title: "Subpoena" },
        { title: "Notice of Appearance" },
        { title: "Litigation Hold Notice" },
        { title: "Settlement Agreement" },
        { title: "Mutual Release of Claims" },
        { title: "Consent Order" },
        { title: "Mediation Agreement" },
      ],
    },
    "Estate Planning (Broad)": {
      title: "Estate Planning (Broad)",
      iconKey: "Crown",
      templates: [
        { title: "Last Will and Testament" },
        { title: "Living Will (Advance Directive)" },
        { title: "Revocable Living Trust" },
        { title: "Irrevocable Trust" },
        { title: "Durable Power of Attorney" },
        { title: "Medical Power of Attorney" },
        { title: "HIPAA Authorization" },
        { title: "Do Not Resuscitate (DNR) Order" },
        { title: "Transfer on Death Deed" },
        { title: "Beneficiary Designation Form" },
      ],
    },
    "Cybersecurity & Incident Response": {
      title: "Cybersecurity & Incident Response",
      iconKey: "ShieldIcon",
      templates: [
        { title: "Incident Response Plan" },
        { title: "Security Incident Report Form" },
        { title: "Data Breach Notification Policy" },
        { title: "Vulnerability Disclosure Policy" },
        { title: "Access Control Policy" },
        { title: "Third-Party Security Questionnaire" },
        { title: "Penetration Testing Rules of Engagement" },
        { title: "Information Security Addendum" },
        { title: "Business Continuity & Disaster Recovery Plan" },
        { title: "Key Management Policy" },
      ],
    },
  },
};

export default templates;
